.TH "k9xineplayer" "1"
.if n .ad l
.nh

.SH "NAME"
k9xineplayer \- A movie playing utility

.SH "SYNOPSIS"
.B k9xineplayer
.RI [ Qt-options ]
.RI [ KDE-options ] 
\&...

.SH "DESCRIPTION"
k9copy is a DVD backup utility which allow the copy of one or more titles from a DVD9 to a DVD5.

.SH OPTIONS
.PP
All KDE and Qt
programs accept a some common command-line options. k9copy has no
application-specific options.
.PP

.TP
.BR \-\-`help
Show help about options

.TP
.BR \-\-`help\-qt
Show Qt specific options

.TP 
.BR \-\-`help\-kde
Show KDE specific options

.TP 
.BR \-\-`help\-all
Show all options

.TP
.BR \-\-`author
Show author information

.TP
.BR \-\-`version 
Show version information

.TP
.BR \-\-`license
Show license information

.TP
.BR \-\- 
Indicates end of options

.SH COPYRIGHT
This manual page was written by Steve Stalcup <vorian@ubuntu.com> 
for the \fBKubuntu GNU/Linux\fP system.
